name: Update packages table in README

on:
  push:
    paths:
      - 'package.json'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Update README.md
        run: npm run update:readme

      - name: Commit changes
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        run: |
          git config --global user.name "${BOT_NAME}"
          git config --global user.email "${BOT_EMAIL}"
          git remote set-url origin https://x-access-token:${BOT_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update packages table in README.md" || true
          git push
